kind: PersistentVolume
apiVersion: v1
metadata:
  name: code-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/itc-admin-mbp-15/Projects/hello-minikube/definitions/src"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi