# Create the secret:
# ` kubectl apply -f secret.yaml `
# You can view the secret with the following command:
# ` kubectl -n kube-system get secret digitalocean `
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  access-token: your-api-token
  username: root
  password: root
  apiUrl: "https://my.api.com/api/v1"
    

