commonLabels:
  app: app
configMapGenerator:
- name: app-config
  files:
  - .env  
secretGenerator:
- name: mysql-pass
  literals:
  - username=root
  - password=root
# resources:
#   - mysql-deployment.yaml
#   - wordpress-deployment.yaml
